#!/usr/bin/env php
<?php

define('FONT_FILE', './bicubik.ttf');

// Создание изображения
$img = imagecreatetruecolor(800, 525);

// Создание цвета фона
$bgColor = imagecolorallocate($img, 32, 64, 85);
// и его заливка. Заливаем от указанных координат
imagefill($img, 0, 0, $bgColor);

// Цвет текста и линий
$white = imagecolorallocate($img, 255, 255, 255);

// Верхняя линия
imagerectangle($img, 100, 80, 700, 90, $white);
imagefilltoborder($img, 101, 81, $white, $white);

// левая линия
imagerectangle($img, 100, 90, 110, 400, $white);
imagefilltoborder($img, 101, 91, $white, $white);

// нижняя линия
imagerectangle($img, 100, 400, 700, 410, $white);
imagefilltoborder($img, 101, 401, $white, $white);

// правая линия
imagerectangle($img, 690, 400, 700, 180, $white);
imagefilltoborder($img, 691, 201, $white, $white);

// PHP и подчеркивание
imagefttext($img, 100, 0, 240, 200, $white, FONT_FILE, 'PHP');
imagerectangle($img, 200, 220, 600, 230, $white);
imagefilltoborder($img, 201, 221, $white, $white);


$config = [
    'size' => 60,
    'offset-x' => 0,
    'offset-y' => 0,
    'text' => '',
];

$next = null;
foreach($argv as $arg) {
    switch ($arg) {

        case '--text':
            $next = 'text';
            break;

        case '--font-size':
            $next = 'size';
            break;

        case '--offset-x':
            $next = 'offset-x';
            break;

        case '--offset-y':
            $next = 'offset-y';
            break;

        default:
            if (!is_null($next) && isset($config[$next])) {
                $config[$next] = $arg;
            }
    }
}

// На случай, если текст обернули не в двойной апостроф ("), а в одинарный (')
$config['text'] = str_replace('\n', "\n", $config['text']);

imagefttext($img, $config['size'], 0,
    200 + $config['offset-x'],
    330 + $config['offset-y'],
    $white, FONT_FILE, $config['text']);

imagepng($img, 'result.png');

